version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/finance-tracker
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file: .env
    environment:
      - MONGO_INITDB_DATABASE=finance-tracker
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: 